In [35]:
import pandas as pd
import numpy as np

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is non-numeric
        'Feature2': [5.5, 6.7, 8.9]}

##ANSWER-1:  Fill Non Numeric with 'NaN'
##----------------------------------------------------
df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')
##Remarks:
## In Pandas, the parameter errors='coerce' (used in pd.to_numeric()) means:
## If a value cannot be converted to a number, replace it with NaN (Not a Number) instead of raising an error.
print("With 'NaN' values\n",df,"\n")

##ANSWER-2:  Fill 'Non Numeric' with '0'
##----------------------------------------------------
df['Feature1'].fillna(0, inplace=True)
print("Replacing NaN with '0':\n",df)

With 'NaN' values
    Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9 

Replacing NaN with '0':
    Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       0.0       8.9


In [36]:
#Explanation: Missing values are filled with the column mean.
import pandas as pd

data = {'A': [1, 2, None],
        'B': [4, None, 6]}

df1 = pd.DataFrame(data)
mean_value = df.mean()
df1.fillna(mean_value)

df2 = pd.DataFrame(data)
df2.fillna(df2.mean(), inplace=True)  # Use inplace=True to modify the DataFrame

print("Before:\n",df1,"\n")
print("AFter:\n",df2)


Before:
      A    B
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0 

AFter:
      A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [47]:
#3.from sklearn.linear_model import LinearRegression
#3.from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()

##Answer:1
#Make the X to 2D.  Then proceed.
X1 = np.array([[1], [2], [3], [4], [5]])  
model.fit(X1, y)
print("Answer for Method-1:\n",model.predict([[6]]))  # Predict for new value

##Answer:2
X2 = X.reshape(-1, 1)
model.fit(X2, y)
print("Answer for Method-2:\n",model.predict([[6]]))  # Predict for new value



Answer for Method-1:
 [12.]
Answer for Method-2:
 [12.]


In [62]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D

#Method-1: Make the array to 2D by reshape
X1 = data.reshape(-1, 1)
#Method-2: Make the array to 2D by reshape
X2 = np.array([[10], [20], [30], [40], [50]])  # Error: Should be 2D

scaler = StandardScaler()


scaled_data = scaler.fit_transform(X1)
print("Result by Method-1\n",scaled_data,"\n")

scaled_data = scaler.fit_transform(X2)
print("Result by Method-2\n",scaled_data)



Result by Method-1
 [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]] 

Result by Method-2
 [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [79]:
#5.
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

##Approach-1
y1 = [1, 0, 1]   # 'no'→0, 'yes'→1
print(y1)
##Approach-2
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
print(y_encoded)


##Result for Approach-1----------------------
model = LogisticRegression()
model.fit(X, y1)
print("Answer for approach-1:\n",model.predict([[4, 5]]),"\n")

##Result for Approach-1----------------------
model2 = LogisticRegression()
model2.fit(X, y_encoded)
print("Answer for approach-2:\n",model2.predict([[4, 5]]),"\n")

[1, 0, 1]
[1 0 1]
Answer for approach-1:
 [1] 

Answer for approach-2:
 [1] 



In [81]:
#6: ans -Explanation: Convert categorical data into binary columns.
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])  # ✅ Use double brackets to make it 2D

print(encoded.toarray(),"\n")
print(encoder.get_feature_names_out(['Category']))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

['Category_A' 'Category_B' 'Category_C']


In [82]:
#6.ans-No error, and correctly split data.

# Make sure y has 4 values (one label per row in X).

from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]  #4 labels

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train:", X_train)
print("y_train:", y_train)
print("X_test:", X_test)
print("y_test:", y_test)


X_train: [[7, 8], [1, 2], [5, 6]]
y_train: [1, 0, 0]
X_test: [[3, 4]]
y_test: [1]


In [83]:
#Q7: It is same as #Q5 .  Hence omitted

In [96]:
##8: Variaous approaches to replace NaN values with '0'

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Create dataset with NaN
X_train = pd.DataFrame([[1, 2], [3, np.nan], [5, 6]])
y_train = pd.Series([10, 20, 30])

# Fill missing values with column mean

##Approach-1
X_train = X_train.fillna(0)
# X_train.fillna(0, inplace=True)

##Approach-2
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="mean")
X_train_imputed = imputer.fit_transform(X_train)



# Train model
model = LinearRegression()
model.fit(X_train, y_train)

print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
prediction = model.predict([[3, 4]])
print("Predicted Output:", prediction)

Coefficients: [5.00000000e+00 5.43895982e-16]
Intercept: 5.000000000000002
Predicted Output: [20.]


In [97]:
#Q9: DecisionTreeClassifier requires numeric labels, not strings.

from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]

# Convert string labels to numeric
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y_train)  # 'ham'->0, 'spam'->1

# Train the model
model = DecisionTreeClassifier()
model.fit(X_train, y_encoded)

# Predict example
pred = model.predict([[2, 3]])
print("Predicted (encoded):", pred)
print("Predicted (original):", encoder.inverse_transform(pred))


Predicted (encoded): [1]
Predicted (original): ['spam']


In [114]:
#10.from sklearn.svm import SVC
from sklearn.svm import SVC


X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]


model = SVC()
model.fit(X_train_scaled, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


[0]
